server.port=8080
spring.application.name=yu
spring.ai.openai.base-url=https://api.siliconflow.cn
spring.ai.openai.api-key=${PATH_ai_siliconflow_api}

spring.ai.openai.audio.speech.options.model=FunAudioLLM/CosyVoice2-0.5B
spring.ai.openai.audio.speech.options.response-format=mp3
spring.ai.openai.audio.speech.options.voice=fnlp/MOSS-TTSD-v0.5:diana
spring.ai.openai.audio.speech.options.speed=0.8

spring.ai.openai.audio.transcription.options.model=TeleAI/TeleSpeechASR




