server:
  port: 8080 #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    include: redis
    active: dev
  config:
    import:
      - classpath:mysql.yaml
      - classpath:redis.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB




