# 服务端口与应用名
server.port=8080
spring.ai.dashscope.base-url=https://dashscope.aliyuncs.com
spring.ai.dashscope.api-key=${PATH_ai_aliyun_api}

#视觉理解qwen3.5-flash
#spring.ai.dashscope.chat.options.model=qwen3.5-flash-2026-02-23
spring.ai.dashscope.chat.options.model=qwen-flash-2025-07-28
spring.ai.dashscope.chat.options.max-tokens=1024

#多模态向量tongyi-embedding-vision-flash-2026-03-06
spring.ai.dashscope.embedding.options.model=text-embedding-v4
spring.ai.dashscope.embedding.options.dimensions=1024
spring.ai.dashscope.embedding.options.text-type=float

spring.ai.dashscope.audio.speech.options.model=sambert-zhiqi-v1
spring.ai.dashscope.audio.speech.options.format=mp3
spring.ai.dashscope.audio.speech.options.speed=0.8
spring.ai.dashscope.audio.speech.options.volume=60

spring.ai.dashscope.audio.transcription.options.model=paraformer-v2

