server.port=7070
spring.application.name=yu
spring.ai.dashscope.base-url=https://dashscope.aliyuncs.com
spring.ai.dashscope.api-key=${PATH_ai_aliyun_api}

# 阿里云DashScope 视觉识别配置
spring.ai.dashscope.chat.options.model=visual-ai
# 阿里云DashScope语音合成配置
spring.ai.dashscope.audio.speech.options.model=sambert-zhimao-v1
spring.ai.dashscope.audio.speech.options.format=mp3
spring.ai.dashscope.audio.speech.options.speed=1.0
spring.ai.dashscope.audio.speech.options.volume=60


