# 服务端口与应用名
server.port=8080
spring.ai.dashscope.base-url=https://dashscope.aliyuncs.com
spring.ai.dashscope.api-key=${PATH_ai_aliyun_api}

spring.ai.dashscope.audio.speech.options.model=sambert-zhiqi-v1
spring.ai.dashscope.audio.speech.options.format=mp3
spring.ai.dashscope.audio.speech.options.speed=0.8
spring.ai.dashscope.audio.speech.options.volume=60
