server.port=8088
spring.application.name=yu
spring.ai.dashscope.base-url=https://dashscope.aliyuncs.com
spring.ai.dashscope.api-key=${PATH_ai_aliyun_api}

# 阿里云DashScope语音合成配置
spring.ai.dashscope.audio.synthesis.options.model=sambert-zhimao-v1
spring.ai.dashscope.audio.synthesis.options.response-format=mp3
spring.ai.dashscope.audio.synthesis.options.pitch=1.0
