server.port=8080
spring.application.name=graph
spring.ai.openai.base-url=https://api-inference.modelscope.cn
spring.ai.openai.api-key=${PATH_ai_qwen_api}
spring.ai.openai.chat.options.model=Qwen/Qwen3-14B
